create table tb_document (document_status smallint check (document_status between 0 and 2), id bigserial not null, user_id bigint, name varchar(255), primary key (id));
create table tb_user (id bigserial not null, name varchar(255), primary key (id));
alter table if exists tb_document add constraint FKecdlxa6scehpjw829nf8572mu foreign key (user_id) references tb_user;
INSERT INTO tb_user(name) VALUES ('Anisio Ferreira Suitsu');
INSERT INTO tb_user(name) VALUES ('Fabio Jose dos Santos');
INSERT INTO tb_user(name) VALUES ('Julio Cezar Morais Vicente');
INSERT INTO tb_user(name) VALUES ('Marcos Librelon Raia');
INSERT INTO tb_user(name) VALUES ('Rosemeire Bonfim de Almeida');
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CNH', 1, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CPF', 1, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('Extrato', 1, 0);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('RG', 2, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CPF', 2, 2);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CNH', 3, 2);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('Extrato', 3, 0);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CNH', 4, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CPF', 4, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('Escritura', 4, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CNH', 5, 2);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CPF', 5, 2);
create table tb_document (document_status tinyint, id bigint not null auto_increment, user_id bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table tb_user (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
alter table tb_document add constraint FKecdlxa6scehpjw829nf8572mu foreign key (user_id) references tb_user (id);
INSERT INTO tb_user(name) VALUES ('Anisio Ferreira Suitsu');
INSERT INTO tb_user(name) VALUES ('Fabio Jose dos Santos');
INSERT INTO tb_user(name) VALUES ('Julio Cezar Morais Vicente');
INSERT INTO tb_user(name) VALUES ('Marcos Librelon Raia');
INSERT INTO tb_user(name) VALUES ('Rosemeire Bonfim de Almeida');
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CNH', 1, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CPF', 1, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('Extrato', 1, 0);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('RG', 2, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CPF', 2, 2);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CNH', 3, 2);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('Extrato', 3, 0);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CNH', 4, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CPF', 4, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('Escritura', 4, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CNH', 5, 2);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CPF', 5, 2);
create table tb_document (document_status tinyint, id bigint not null auto_increment, user_id bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table tb_user (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
alter table tb_document add constraint FKecdlxa6scehpjw829nf8572mu foreign key (user_id) references tb_user (id);
INSERT INTO tb_user(name) VALUES ('Anisio Ferreira Suitsu');
INSERT INTO tb_user(name) VALUES ('Fabio Jose dos Santos');
INSERT INTO tb_user(name) VALUES ('Julio Cezar Morais Vicente');
INSERT INTO tb_user(name) VALUES ('Marcos Librelon Raia');
INSERT INTO tb_user(name) VALUES ('Rosemeire Bonfim de Almeida');
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CNH', 1, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CPF', 1, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('Extrato', 1, 0);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('RG', 2, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CPF', 2, 2);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CNH', 3, 2);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('Extrato', 3, 0);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CNH', 4, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CPF', 4, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('Escritura', 4, 1);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CNH', 5, 2);
INSERT INTO tb_document(name, user_id, document_status) VALUES ('CPF', 5, 2);
